[project]
name = "pubg_mortar_calculator"
version = "4.6.2"
description = "A tool to calculate the range of a shot for mortar."
authors = [{ name = "IZomBie", email = "patrik009009@gmail.com" }]
license = { text = "You can use everything." }
readme = "README.md"
requires-python = ">=3.13, <3.14"
dependencies = [
    "opencv-python>=4.10.0.84",
    "mss>=10.0.0",
    "screeninfo>=0.8.1",
    "customtkinter>=5.2.2",
    "pillow>=11.1.0",
    "keyboard>=0.13.5",
    "pyttsx3>=2.98",
    "mouse>=0.7.1",
    "pygetwindow>=0.0.9",
    "pip>=25.2",
    "onnxruntime>=1.23.2",
    "pytest>=9.0.2",
]

[project.scripts]
pubg_mortar_calculator = "pubg_mortar_calculator.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "matplotlib>=3.11.1",
    "onnxscript>=0.7.1",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu126"

[tool.hatch.build.targets.wheel]
packages = [
    "pubg_mortar_calculator",
]
