from .calculation_data_block import CalculationDataBlock
from .dictor_settings_block import DictorSettingsBlock
from .elevation_detector_block import ElevationDetectorBlock
from .general_settings_block import GeneralSettingsBlock
from .grid_detector_block import GridDetectorBlock
from .mark_detector_block import MarkDetectorBlock
from .minimap_detector_block import MinimapDetectorBlock
from .overlay_settings_block import OverlaySettingsBlock
